
AWSTemplateFormatVersion: '2010-09-09'
Description: 'test template'

Parameters:
 
 customerstring:
    Description: Customer String 
    Type: String

 number:
    Description: Number of vpn
    Type: String  

 cgwipadress:
    Description: ip 
    Type: String

 vpgid:
    Description: vpgid
    Type: String



Resources: 


  VPNConnection: 
      Type: AWS::EC2::VPNConnection
      DeletionPolicy: Retain
      Properties: 
        Type: ipsec.1
        Tags: 
        - Key: "Name"
          Value: !Join
                    - '-'
                    - - 'VPN'
                      - !Ref customerstring
                      - !Ref number
        StaticRoutesOnly: true
        CustomerGatewayId: 
          !Ref cgw-0802f26c0b94ca769
        VpnGatewayId: 
          !Ref vpgid
 




  # #!PyPlate
  # output = []
  # for ip in params['RouteEntries']:
  #   for i in range[0:Fn::Length : Array]:
  #     output[name] = { "Type": "AWS::EC2::VPNConnectionRoute", "Properties": {"DestinationCidrBlock": ip ,"VpnConnectionId":{ "Ref" : "VPNConnection" }} }
      

